### PR TITLE
Dev documentation, removed useFetchProjectData.jsx

### PR DESCRIPTION
**Pull request by natekim27**
- Wrote out DEVELOPER.md and created a docs folder in root directory.
- Removed the useFetchProjectData.jsx file as it wasn't used.

### CODE REVIEW

**Review by jyoung3131 — APPROVED** [review]
LGTM. Will ask Kate to check and see if we missed anything for the docs before merging!

**Comment by jyoung3131** [comment]
Hi @natekim27  - can you help fill in the customizing sections on color/logos for that doc? I've moved them over from my other PR, which we may not need (I think that is the main difference with your commits here).

**Review by krachwal — APPROVED** [review]
You do mention a blog post near the end but I don't see a link. Otherwise good.

**Review by jyoung3131 — APPROVED** [review]
Looks good - thank you!

**Pull request merged**
